name: RingTool CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pre-commit pytest

    - name: Run linter
      run: |
        ruff check .

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
        run: pytest

  check_pyc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find .pyc files
        id: find_pyc
        run: |
          find . -name "*.pyc" -print0 | while IFS= read -r -d $'\0' file; do
            echo "::warning file=$file::Found a .pyc file."
            echo "found_pyc=true" >> "$GITHUB_OUTPUT"
          done

      - name: Fail if .pyc files are found
        if: steps.find_pyc.outputs.found_pyc == 'true'
        run: |
          echo "Error: .pyc files should not be included in the repository."
          exit 1